### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by bohong65** [tengfei-xy/siyuan-plugin-share-system#1]
挺有意思的项目，一直期待这一类发布笔记的插件，但是试了一下发布后页面排版乱了。对比了很多发布方案最大的痛点就是排版格式，比较好的解决思路应该是将笔记导出为html然后发布到web，希望开发者后续可以从这个角度尝试。另一个很重要的功能就是双链，希望发布后的网页依然能以超链接的形式还原双链。
当然最重要的还是发布的web页排版保持与思源内一致，别的都可以忍

**Comment by tengfei-xy** [comment]
谢谢使用哈，由于无法测试全面，造成在您的场景下发布排班比较乱，后续我将继续测试。“另一个很重要的功能就是双链，希望发布后的网页依然能以超链接的形式还原双链。”指的是，访问分享链接后，链接不会变化的意思嘛？

**Comment by tengfei-xy** [comment]
发现是windows端的jszip打包出现问题，macos端是正常的。由于之前测试使用了缓存，于是这个bug被忽略了。。

**Comment by tengfei-xy** [comment]
windows环境打包问题已修复，最新版本v0.0.3 ~

> 发现是windows端的jszip库打包资源文件出现问题，mac端是正常的。由于之前测试使用了缓存，于是这个bug被忽略了。。

**Comment by bohong65** [comment]
> 谢谢使用哈，本项目的实现原理就如您所说。但是从客户端直接导出时，并不含有index.html。而这个文件来自思源笔记的客户端生成。由于无法测试全面，造成在您的场景下发布排班比较乱，后续我将继续测试。“另一个很重要的功能就是双链，希望发布后的网页依然能以超链接的形式还原双链。”指的是，访问分享链接后，链接不会变化的意思嘛？

![image](https://github.com/tengfei-xy/siyuan-plugin-share-system/assets/14939297/608259d3-a902-4e75-8a74-f21cf7456b28)
如图当我发布示例文档页面时，希望示例文档中的引用块页面同时发布，在web页面中点击“双链1”转跳到“示范双链1”。
同时感谢windows端修复！

**Comment by tengfei-xy** [comment]
这个双链的功能超过了思维笔记（3.0.7及以下版本的）的导出功能，也超过了本项目的静态发布的目标。这个问题需要设立新的项目了，设想了一种由反向代理和简化的窗口选项（仅显示文档页面）的本地应用程序，似乎是个更好选择。
