### ISSUE TITLE
不兼容最新版本的思源，服务器版本的

### ISSUE THREAD

**Issue by Mowen-M** [tengfei-xy/siyuan-plugin-share-system#12]
无法兼容![image](https://github.com/user-attachments/assets/d07036b0-629d-4c60-b253-58fdd238fece)![image](https://github.com/user-attachments/assets/17504ec0-3d06-4b61-85ac-1d9717af12a3)

**Comment by Mowen-M** [comment]
希望支持！比另一个好用！那个是静态的，还是动态的好使

**Comment by tengfei-xy** [comment]
我看看

**Comment by tengfei-xy** [comment]
服务器版本是指的是，思源笔记运行在远程服务器，然后客户端ipad去访问的吗？

**Comment by Mowen-M** [comment]
> 服务器版本是指的是，思源笔记运行在远程服务器，然后客户端ipad去访问的吗？

对，docker的思源，然后远程访问的，用的webdev同步。官方的源，可能是更新太快了，没跟上hhhh

**Comment by tengfei-xy** [comment]
我先熟悉下代码，好久没动了😂

**Comment by Mowen-M** [comment]
> 我先熟悉下代码，好久没动了😂

好嘞，坐等

**Comment by tengfei-xy** [comment]
欢迎品尝最新版（[v1.3.0](https://github.com/tengfei-xy/siyuan-plugin-share-system/releases/tag/v1.3.0)），此版本支持了 docker，等待插件商店发布中。

**Comment by Mowen-M** [comment]
> 欢迎品尝最新版（[v1.3.0](https://github.com/tengfei-xy/siyuan-plugin-share-system/releases/tag/v1.3.0)），此版本支持了 docker，等待插件商店发布中。

牛牛，速度
