### ISSUE TITLE
docker没有tag，如何在NAS中部署呢？

### ISSUE THREAD

**Issue by Dotaallstars** [tengfei-xy/siyuan-plugin-share-system#13]
可否发布至dockerhub？感谢~

**Comment by tengfei-xy** [comment]
这个问题的话，目前docker容器有三个，一个web服务器，一个数据库，一个应用，架构很复杂，我想整合到一个应用里，容器启动也方便。完成了这一步，我再发不到dockerhub吧。

**Comment by tengfei-xy** [comment]
参考https://hub.docker.com/repository/docker/tengfeixy/spss_engine/general
