### ISSUE TITLE
建议能提供已分享页面的集中管理功能

### ISSUE THREAD

**Issue by jidenanian** [tengfei-xy/siyuan-plugin-share-system#14]
已分享页面多了以后，希望能够提供一个集中管理的功能，方便删除一些不再分享的页面

**Comment by tengfei-xy** [comment]
阁下有多少页面😂

**Comment by liuxingar** [comment]
我猜需求痛点可能是现在不清楚哪些页面做了分享，笔记多起来后，逐个查找基本不可能

**Comment by tengfei-xy** [comment]
目前的话，有提供几个接口来查看、更新表，但是做得很简单。

**Comment by tengfei-xy** [comment]
下个版本再更新吧

**Comment by cly2625** [comment]
支持！看到了您分享的wolai笔记，感谢您的分享精神，另外您使用自己的服务器提供服务也是要耗费的，请问能都增加大赏页面？

**Comment by tengfei-xy** [comment]
> 支持！看到了您分享的wolai笔记，感谢您的分享精神，另外您使用自己的服务器提供服务也是要耗费的，请问能都增加大赏页面？

**Comment by cly2625** [comment]
就是像其他插件作者一样提供支付宝微信的打赏二维码



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月14日 10:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [tengfei-xy/siyuan-plugin-share-system] 建议能提供已分享页面的集中管理功能 (Issue #14) |

支持！看到了您分享的wolai笔记，感谢您的分享精神，另外您使用自己的服务器提供服务也是要耗费的，请问能都增加大赏页面？
大赏页面指的是？

**Comment by tengfei-xy** [comment]
![IMG_5532](https://github.com/user-attachments/assets/2015f42b-940e-47b7-9ec4-843ccfcc446b)
![IMG_5533](https://github.com/user-attachments/assets/5ac23f59-f434-43c7-b439-a7e4e6555e4e)

**Comment by tengfei-xy** [comment]
已发布,v2.2.0，等待集市更新。
