### ISSUE TITLE
Add Support for Custom Domains and Enable HTTPS for Enhanced Security

### ISSUE THREAD

**Issue by UsmanTechJive** [tengfei-xy/siyuan-plugin-share-system#17]
I would like to request the ability to add our own custom domain, so the final URL would look like:

customdomain.com/documentEncryptedID

Additionally, the current setup only works with HTTP, which is not recommended for security best practices. Could you please add an option for custom domains and ensure HTTPS support?

![image](https://github.com/user-attachments/assets/93981f00-a7bb-4f09-bdfb-81ef59c6a10d)

**Comment by tengfei-xy** [comment]
You are right, https is the best practice. But if you have security requirements, I suggest you build a server by yourself through [docker](https://github.com/tengfei-xy/siyuan-plugin-share-system-engine). The server I provide (in China) does not include a domain name. In China, domain name registration and filing is a complicated matter. I am too lazy to file it.

**Comment by tengfei-xy** [comment]
In the latest version (v2.3.1), a new server address (including https) is used, which will improve the user experience.
