### ISSUE TITLE
Improve Share Speed and Add Shared Indicator in Breadcrumb Area

### ISSUE THREAD

**Issue by UsmanTechJive** [tengfei-xy/siyuan-plugin-share-system#18]
When I click on 'Create/Update Link,' it takes a too much amount of time (sometimes 30 min and more) to share the document on the web and display the share address and sometimes its not displaying the shared address even after too much time. Could you make this process faster, similar to the sharing feature in Capacities or Notion? In those apps, the document is instantly shared on the web, and a secret share link is provided almost immediately.

Please take a look at the Capacities sharing feature—it is very user-friendly and efficient. I would be grateful if we could have a similar experience in SiYuan.

https://github.com/user-attachments/assets/a4951b99-8dd5-4aa3-af8a-741f0fe86f4b

Once the content has been shared in Capacities, the user can see a beautiful shared indicator in the breadcrumb area. I would love to see a similar feature in SiYuan so that we can easily know which documents have been shared and which have not.

![image](https://github.com/user-attachments/assets/a7d249d9-91e4-4ef5-9c03-19dca24c1ff2)

Last but not least, please change the icon to the one shown in the image below. It looks better, in my opinion.

![image](https://github.com/user-attachments/assets/7174c728-39e2-4195-b28e-a24c40f07141)

This is the current icon which doesn't looks good to me.

![image](https://github.com/user-attachments/assets/7b3fa82a-1afb-4b0a-8a45-c9269e8c8dcb)

Thank you for considering this improvement!

**Comment by tengfei-xy** [comment]
The upload is slow, mainly because the connection to the server (the default is 124.223.15.220) is slow. I guess your client is not in China, but the server is in China, and I don't have servers in other countries, so the sharing is very slow. You can consider using [docker](https://github.com/tengfei-xy/siyuan-plugin-share-system-engine) to build your own server.

**Comment by tengfei-xy** [comment]
Thanks, your icon suggestion is very good, I will update the image in the next version.

**Comment by dongshanxia** [comment]
分享页面多了以后  占用资源 公共部分的js有好多  可以压缩空间俺  有没有办法压缩呢  比如公共空间提取出来

**Comment by tengfei-xy** [comment]
> 分享页面多了以后 占用资源 公共部分的js有好多 可以压缩空间俺 有没有办法压缩呢 比如公共空间提取出来

如果你是为了节省硬盘空间，快速的方法，可以参考`find 资源目录 -name 'resources.zip' | xargs -n1  /usr/bin/rm`搜索资源目录的压缩包并删除。我这边六百多个压缩包，占用了7.7G。如果纯粹为了提取公共文件，那么需要修改程序了。

**Comment by tengfei-xy** [comment]
> When I click on 'Create/Update Link,' it takes a too much amount of time (sometimes 30 min and more) to share the document on the web and display the share address and sometimes its not displaying the shared address even after too much time. Could you make this process faster, similar to the sharing feature in Capacities or Notion? In those apps, the document is instantly shared on the web, and a secret share link is provided almost immediately.
> 
> Please take a look at the Capacities sharing feature—it is very user-friendly and efficient. I would be grateful if we could have a similar experience in SiYuan.
> 
>  Centered.Document.View.Web.Sharing.Issue.12978.siyuan-note-siyuan.mp4 
> Once the content has been shared in Capacities, the user can see a beautiful shared indicator in the breadcrumb area. I would love to see a similar feature in SiYuan so that we can easily know which documents have been shared and which have not.
> 
> ![image](https://private-user-images.githubusercontent.com/36538038/382773764-a7d249d9-91e4-4ef5-9c03-19dca24c1ff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjQxNzEsIm5iZiI6MTczMzc2Mzg3MSwicGF0aCI6Ii8zNjUzODAzOC8zODI3NzM3NjQtYTdkMjQ5ZDktOTFlNC00ZWY1LTljMDMtMTlkY2EyNGMxZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE3MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZDRlMTc3YmQ5NWM2ZmUyZDJjMmQ2YmUxYjJiZGE5ZmNiN2MxZmQ3YTZmYmIwYWJiZWM4YzczNTk2MzE2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rY3G5TgA7HVfUI8nUeNKb0msbxzWlhO0kQSLunWqwo4)
> 
> Last but not least, please change the icon to the one shown in the image below. It looks better, in my opinion.
> 
> ![image](https://private-user-images.githubusercontent.com/36538038/382775268-7174c728-39e2-4195-b28e-a24c40f07141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjQxNzEsIm5iZiI6MTczMzc2Mzg3MSwicGF0aCI6Ii8zNjUzODAzOC8zODI3NzUyNjgtNzE3NGM3MjgtMzllMi00MTk1LWIyOGUtYTI0YzQwZjA3MTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE3MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzODEzNjMzOGFmZjQwZDU5MWIzNWUxMjE5MjMxNDIyZWUwNWY3YTFlMzRlMTdjZGUxNTBhZWFlYTg3MGY4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7x-CxHqT8P8sYUUvkFis1hS8-sz2yw78bxP-yYW3MBs)
> 
> This is the current icon which doesn't looks good to me.
> 
> ![image](https://private-user-images.githubusercontent.com/36538038/382775532-7b3fa82a-1afb-4b0a-8a45-c9269e8c8dcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjQxNzEsIm5iZiI6MTczMzc2Mzg3MSwicGF0aCI6Ii8zNjUzODAzOC8zODI3NzU1MzItN2IzZmE4MmEtMWFmYi00YjBhLThhNDUtYzkyNjllOGM4ZGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE3MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjcyMWQ5ZWQ2N2Y5YjE0OWFlYmQ3NWVlODMwZTIyMDNlMjZjMjNkNGM5MWMzZjQ2YTk5ZTE4MmVhNmQxOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HfMDhP2f6W90bv9Hv7gCqJcPPKNZa91TbPGXAOw68MM)
> 
> Thank you for considering this improvement!

In the latest version (v2.3.1), a new server address (including https) is used, which will improve the user experience.
