### ISSUE TITLE
Add Support for English Notifications

### ISSUE THREAD

**Issue by UsmanTechJive** [tengfei-xy/siyuan-plugin-share-system#19]
Could you please add support for English notifications? That would be incredibly helpful for many people.

![image](https://github.com/user-attachments/assets/8495a14a-a10a-4e3d-a3a8-4223bea46a83)

![image](https://github.com/user-attachments/assets/bf32a3cb-4709-477d-b5ac-3579b3e146ba)

![image](https://github.com/user-attachments/assets/637dcbdc-3e5a-4bc4-9896-8b0806417f16)

**Comment by tengfei-xy** [comment]
Okay, let me handle it.

**Comment by tengfei-xy** [comment]
commit on [支持英语的提示输出](https://github.com/tengfei-xy/siyuan-plugin-share-system/commit/28eac5a4bb9918bf5f6f42880f857f80049ca6ae),Will be released in the next version update
