### ISSUE TITLE
请问一下这个现在还能使用吗？

### ISSUE THREAD

**Issue by Chenm4** [tengfei-xy/siyuan-plugin-share-system#25]
我现在显示后台访问失败。也没办法点击创建更新链接。

**Comment by tengfei-xy** [comment]
可以的，在插件中，您的插件使用的服务器地址是哪个？

**Comment by tengfei-xy** [comment]
如果不是最新版，请更新到最新版。

**Comment by Chenm4** [comment]
> 可以的，在插件中，您的插件使用的服务器地址是哪个？

刚才用默认的成功了下生成分享网址了（但是图片没成功分享）昨天是不知道怎么搞的一直不行。然后我现在用自己搭建的docker的也不行。我服务器上已经运行起来那个docker镜像了，分享系统服务器的后台地址也改成我的了也是不行。显示后台访问失败。
请问https://[raw.githubusercontent.com/tengfei-xy/siyuan-plugin-share-system-engine/refs/heads/main/config.yaml](https://raw.githubusercontent.com/tengfei-xy/siyuan-plugin-share-system-engine/refs/heads/main/config.yaml)这个链接中哪些需要被更改？我目前就更改了一个shareBaseLink改成了我IP地址:25934

**Comment by tengfei-xy** [comment]
1.图片没分享成功，看看是不是后台还在下载中。
2. 从docker启动的话，可以参考[链接](https://github.com/tengfei-xy/siyuan-plugin-share-system-engine#32-docker)，通过命令行参数这种方式开启动docker，不建议docker+配置文件的方式来启动。
3. 需要帮助的话，我可以向日葵远程debug。

**Comment by Chenm4** [comment]
> 1.图片没分享成功，看看是不是后台还在下载中。 2. 从docker启动的话，可以参考[链接](https://github.com/tengfei-xy/siyuan-plugin-share-system-engine#32-docker)，通过命令行参数这种方式开启动docker，不建议docker+配置文件的方式来启动。 3. 需要帮助的话，我可以向日葵远程debug。

但是命令行我一直显示Unable to find image 'tengfeixy/spss_engine:2.3.0' locally。我现在使用的是阿里的镜像源，正常应该是没问题的。您什么时候有空呢，可以加我qq1154760273向日葵远程一下吗，感谢感谢！
