### ISSUE TITLE
是否可以支持docker部署

### ISSUE THREAD

**Issue by liuxingar** [tengfei-xy/siyuan-plugin-share-system#7]
分享确实是刚需，感谢开发者的付出。
版本基本稳定后是否可以支持docker部署，并提供部署说明。

**Comment by tengfei-xy** [comment]
可以的，预计这周或下周发布

**Comment by liuxingar** [comment]
谢谢

**Comment by jim555666888** [comment]
同求，这个插件太好了，期望能支持docker的本地化部署

**Comment by tengfei-xy** [comment]
docker初步测试完成了，一俩天后发布稳定的docker部署文档

**Comment by tengfei-xy** [comment]
谢谢使用～

**Comment by tengfei-xy** [comment]
测试已完成，请转移至
https://github.com/tengfei-xy/siyuan-plugin-share-system-engine
