### ISSUE TITLE
v0.0.7 打包错误，还是 v0.0.6

### ISSUE THREAD

**Issue by TCOTC** [tengfei-xy/siyuan-plugin-share-system#9]

**Comment by tengfei-xy** [comment]
emmm不好意思，包上传错误了

**Comment by tengfei-xy** [comment]
打包完毕好了，估计一个小时后，自动更新思源笔记的oss中，届时重新更新才有效~

**Comment by tengfei-xy** [comment]
感谢提醒！！我就说这段时间，后台怎么没数据，太不小心了，，

**Comment by tengfei-xy** [comment]
引发了一种神秘的bug，让bazzr依然获取到旧版，我重新上传了个v0.0.9试试，[action](https://github.com/siyuan-note/bazaar/actions/runs/8603440497/job/23575338068)
